version: '3.6'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: pg_write_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes: 
      - ./postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  hasura:
    image: hasura/graphql-engine:v2.6.1
    container_name: hasura
    restart: always
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_ADMIN_SECRET: adminsecret
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:root@postgres:5432/pg_write_db
      HASURA_GRAPHQL_DATABASE_URL: postgres://read_user:read_password@postgres:5432/read_only_db
  hasura_loader:
    image: python:3
    container_name: hasura_loader
    command: bash -c 'pip install requests && python /metadata/metadata_loader.py'
    restart: 'no'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      HASURA_URL: http://hasura:8080
      HASURA_GRAPHQL_ADMIN_SECRET: adminsecret
    volumes: 
      - ./metadata:/metadata